/**
 * Titan Pipeline Types
 * Includes: Vision DNA, Physics, Assets, and UI State Management
 */

import type { AppFile } from '@/types/railway';
import type { CritiqueResult } from '@/types/visualCritic';
import type { AgentCommand, SuspendedExecution } from '@/types/autonomy';

// ============================================================================
// REPO CONTEXT TYPES (Ultimate Developer)
// ============================================================================

/**
 * A reusable code pattern extracted from the repository.
 * Used by the Builder to replicate existing patterns rather than hallucinating new ones.
 */
export interface PatternTemplate {
  /** Descriptive name, e.g., "Data Fetching Hook" */
  name: string;
  /** Source file path, e.g., "src/hooks/useApi.ts" */
  sourceFile: string;
  /** The actual template code snippet */
  codeSnippet: string;
}

/**
 * Repository context extracted by the RepoAnalyst.
 * Provides deep understanding of existing codebases for style-consistent generation.
 */
export interface RepoContext {
  /** Content hash for cache invalidation — skip re-analysis if unchanged */
  contentHash: string;
  /** Freeform style guide generated by AI — captures nuance like import ordering */
  styleGuide: string;
  /** Reusable code patterns extracted from the repo */
  patternLibrary: PatternTemplate[];
  /** Files central to the architecture (high import count / core services) */
  criticalFiles: string[];
  /** Detected tech stack (e.g., "Next.js", "Tailwind", "Prisma") */
  techStack: string[];
  /** If true, modifications to criticalFiles require tests first (Zero-Bug integration) */
  criticalFilesRequireTests: boolean;
}

// ============================================================================
// TECH SCOUT TYPES
// ============================================================================

/** Output of the Tech Scout — research-backed technology recommendations */
export interface TechDossier {
  /** Recommended AI models for the project's needs, with rationale */
  aiModels: TechRecommendation[];
  /** Recommended frameworks and libraries (with verified latest versions) */
  frameworks: TechRecommendation[];
  /** New capabilities or APIs relevant to the project */
  emergingCapabilities: string[];
  /** Warnings about deprecated or outdated tech the user might be expecting */
  deprecationWarnings: string[];
  /** Raw search sources used (for transparency) */
  sources: string[];
  /** Timestamp of the research */
  researchedAt: string;
}

export interface TechRecommendation {
  name: string;
  category: 'ai-model' | 'framework' | 'library' | 'api' | 'service';
  recommendation: string;   // Why this is recommended
  latestVersion?: string;   // Verified latest stable version
  alternatives?: string[];  // Other options considered
  confidence: 'high' | 'medium' | 'low';
}

// ============================================================================
// BLUEPRINT PLANNER TYPES
// ============================================================================

/** Output of the Blueprint Planner — verified phased build instructions */
export interface BlueprintPlan {
  /** Ordered build phases, each covering a set of features */
  phases: BlueprintPhase[];
  /** Confirmed tech stack (from Tech Dossier + planner decisions) */
  techStack: string[];
  /** Self-review summary: how the planner verified coverage */
  coverageReport: string;
  /** Features from the original concept that were initially missed, then added */
  missedItems: string[];
  /** Overall complexity assessment */
  totalEstimatedComplexity: 'low' | 'medium' | 'high';
}

/** A single build phase in the Blueprint */
export interface BlueprintPhase {
  /** Phase name, e.g. "Core Layout & Navigation" */
  name: string;
  /** Build priority (1 = first) */
  priority: number;
  /** Exact features from the concept assigned to this phase */
  features: string[];
  /** React components to create in this phase */
  components: string[];
  /** User interactions to implement */
  interactions: string[];
  /** Relevant tech recommendations from the dossier */
  techNotes: string[];
}

// ============================================================================
// UI & STATE MANAGEMENT TYPES
// ============================================================================

export type PipelineStepName =
  | 'scouting'
  | 'routing'
  | 'surveying'
  | 'planning'
  | 'physicist'
  | 'photographer'
  | 'assembling'
  | 'polishing';

export type PipelineStepStatus = 'idle' | 'running' | 'completed' | 'error';

export const PIPELINE_STEP_LABELS: Record<PipelineStepName, string> = {
  scouting: 'Researching Technology Stack',
  routing: 'Analyzing Intent',
  surveying: 'Reverse Engineering UI',
  planning: 'Planning Build Phases',
  physicist: 'Extracting Motion',
  photographer: 'Generating Material Assets',
  assembling: 'Synthesizing Code',
  polishing: 'Polishing Code Quality',
};

export interface PipelineProgress {
  currentStep: PipelineStepName;
  status: PipelineStepStatus;
  steps: Record<PipelineStepName, { status: PipelineStepStatus; message?: string }>;
}

export const createInitialProgress = (): PipelineProgress => ({
  currentStep: 'scouting',
  status: 'idle',
  steps: {
    scouting: { status: 'idle' },
    routing: { status: 'idle' },
    surveying: { status: 'idle' },
    planning: { status: 'idle' },
    physicist: { status: 'idle' },
    photographer: { status: 'idle' },
    assembling: { status: 'idle' },
    polishing: { status: 'idle' },
  },
});

// ============================================================================
// INSPECTOR BRIDGE TYPES (used by inspectorBridge.ts + LayoutCanvas)
// ============================================================================

/** Message sent from inspector script in Sandpack iframe to parent */
export interface InspectorMessage {
  type: 'COMPONENT_SELECTED';
  /** data-id attribute value */
  id: string;
  /** HTML tag name */
  tagName: string;
  /** outerHTML of the selected element */
  outerHTML: string;
  /** Bounding rect relative to iframe viewport */
  rect: {
    top: number;
    left: number;
    width: number;
    height: number;
  };
}

/** State returned by the useInspectorBridge hook */
export interface InspectorBridgeState {
  /** ID of the currently selected component (data-id value) */
  selectedComponentId: string | null;
  /** outerHTML of the selected component */
  selectedHTML: string | null;
  /** Tag name of the selected component */
  selectedTagName: string | null;
  /** Bounding rect for positioning FloatingEditBubble */
  selectedRect: { top: number; left: number; width: number; height: number } | null;
  /** Clear selection */
  clearSelection: () => void;
}

// ============================================================================
// INPUT / CONTEXT TYPES
// ============================================================================

/** App context passed from the global store for personalized generation */
export interface AppContext {
  name?: string;
  colorScheme?: string;
  primaryColor?: string;
  style?: string;
}

export interface FileInput {
  filename: string;
  mimeType: string;
  base64: string;
}

/** Mode of the OmniChat interface: 'planning' (brainstorming) or 'building' (executing) */
export type ChatMode = 'planning' | 'building';

/** A comprehensive Vision Document - The Product Requirements Document (PRD) */
export interface VisionDocument {
  name: string;
  overview: string; // Rich, multi-paragraph summary of the entire product vision
  corePurpose: string; // The "why" — what problem this solves and why it matters
  targetAudience: string; // Detailed persona descriptions: who uses this, their needs, pain points
  competitiveEdge: string; // What makes this different from alternatives, unique value proposition
  features: VisionFeature[]; // Comprehensive feature specifications
  userFlow: string; // Narrative, step-by-step user journey describing every screen and transition
  pageBreakdown: string; // Detailed description of each page/screen: what it contains, how it looks, how it behaves
  designSystem: string; // Visual language: palette, typography, spacing philosophy, mood, inspirations, component style
  marketAnalysis?: string; // (Legacy) Combined market analysis — prefer corePurpose/targetAudience/competitiveEdge
}

export interface VisionFeature {
  id: string;
  title: string;
  userStory: string; // "As a [user], I want to [action] so that [benefit]"
  description: string; // Rich, multi-sentence explanation of what this feature does and how it works
  behavior: string; // Detailed description of how the feature behaves: interactions, animations, states, responses
  acceptanceCriteria: string[]; // Concrete, testable conditions that must be true for this feature to be "done"
  edgeCases: string; // What happens in unusual scenarios: empty states, errors, edge conditions
  uxNotes: string; // How this feature should feel: speed, feedback, transitions, microinteractions
  complexityLevel: 'low' | 'medium' | 'high';
}

/** Response shape from the /api/layout/vision route */
export interface VisionBoardResponse {
  reply: string;
  visionUpdate?: Partial<VisionDocument>;
}

export interface PipelineInput {
  files: FileInput[];
  instructions: string;
  currentCode: string | null;
  appContext?: AppContext;
  /** Skip the vision healing loop (default: false) */
  skipHealing?: boolean;
  /** Pre-analyzed repo context for style-consistent code generation (Ultimate Developer mode) */
  repoContext?: RepoContext;
  /** Research-backed tech recommendations from the Tech Scout */
  techDossier?: TechDossier;
  /** Verified phased build plan from the Blueprint Planner */
  blueprintPlan?: BlueprintPlan;
}

// ============================================================================
// PIPELINE LOGIC TYPES
// ============================================================================

/** A node in the Surveyor's recursive DOM tree output */
export interface DomTreeNode {
  type: string;
  id?: string;
  styles?: Record<string, string>;
  text?: string;
  children?: DomTreeNode[];
  hasCustomVisual?: boolean;
  extractionBounds?: {
    top: number;
    left: number;
    width: number;
    height: number;
  };
  iconSvgPath?: string;
  /** Allow additional properties from AI output */
  [key: string]: unknown;
}

export interface VisualManifest {
  file_index: number;
  canvas?: {
    width: number;
    height: number;
    background?: string;
  };
  global_theme?: {
    colors?: string[];
    fonts?: string[];
    dom_tree?: DomTreeNode;
    assets?: string[];
  };
  measured_components: Array<{
    type: string;
    text?: string;
    box: { x: number; y: number; w: number; h: number };
    colors?: string[];
  }>;
}

export interface MotionPhysics {
  component_motions: Array<{
    id: string;
    velocity: { x: number; y: number };
    mass: number;
    spring: { stiffness: number; damping: number };
  }>;
}

export interface ComponentStructure {
  layout_strategy: 'flex' | 'grid' | 'absolute';
  tree: Array<{
    type: string;
    id: string;
    props: Record<string, any>;
    children?: any[];
  }>;
}

export interface MergeStrategy {
  mode: 'CREATE' | 'MERGE' | 'EDIT' | 'RESEARCH_AND_BUILD' | 'WORLD_BUILD';
  base_source: 'codebase' | 'file_0' | null;
  file_roles: string[];
  execution_plan: {
    measure_pixels: number[];
    extract_physics: number[];
    preserve_existing_code: boolean;
    generate_assets?: Array<{
      name: string;
      description: string;
      vibe?: string;
      type?: 'texture' | 'image' | 'icon' | 'hdri' | 'environment';
    }>;
    /** Signals 3D mode — Builder appends R3F-specific prompt */
    enable_3d?: boolean;
  };
}

// ============================================================================
// RESULTS
// ============================================================================

export interface PipelineResult {
  files: AppFile[];
  strategy: MergeStrategy;
  manifests: VisualManifest[];
  physics: MotionPhysics | null;
  warnings: string[];
  stepTimings: Record<string, number>;
  /** Visual critique result (if evaluated) */
  critique?: CritiqueResult;
  /** Vision healing loop result (if run) */
  healingResult?: {
    fidelityScore: number;
    iterations: number;
    stopReason: string;
    usedPatching?: boolean;
  };
  /** Avatar Protocol: Command to be executed by the client */
  command?: AgentCommand;
  /** Avatar Protocol: State to persist while waiting for feedback */
  suspendedState?: SuspendedExecution;
}

export interface LiveEditResult {
  success: boolean;
  error?: string;
  updatedCode?: string;
}

// ============================================================================
// OMNICHAT TYPES
// ============================================================================

/** A single message in the OmniChat conversation history */
export interface OmniConversationMessage {
  role: 'user' | 'assistant';
  content: string;
}

/** Request body for the OmniChat endpoint */
export interface OmniChatRequest {
  message: string;
  conversationHistory: OmniConversationMessage[];
  currentCode: string | null;
  appContext?: AppContext;
}

/** Action the AI decides to take after processing a message */
export type OmniChatAction = 'pipeline' | 'autonomy' | 'live-edit' | 'none';

/** Response from the OmniChat endpoint */
export interface OmniChatResponse {
  reply: string;
  action: OmniChatAction;
  actionPayload?: {
    instructions: string;
    selectedDataId?: string;
    /** Skill ID from cache hit — used to update quality score after critique */
    cachedSkillId?: string;
  };
}
